### ISSUE TITLE
Machina: Planet Tech T0

### ISSUE THREAD

**Issue by Cy4Shot** [Cy4Shot/MACHINA#11]
# Description
This task involves creating the first version of the core tech for registering and generating planets with a variety of biomes, features and POIs to explore. Meant to facilitate a vertical slice of biome types for alpha v0.1.

# Aims
- To create a simple and versatile system to - build various types of planets with biomes, features and structures as well as interesting resources to gather.
- To create a scriptable system that allows for easy iteration as well as 3rd party planet types and biomes with datapacks.
- To create a system that provides a unique yet cohesive environment on each playthrough.

# Tasks
- [x] Dynamic Dimension Registration
- [x] Dynamic Biome Registration
- [x] Dynamic Type Registration
- [x] Climate Coherency
- [x] Planet Density Generation
- [x] Planet Surface Generation
- [x] Cave Slopes
- [x] Trees
- [x] Bushes
- [x] Grass
- [x] Ores
- [x] Lakes
- [x] Flowers
- [x] Fruit
- [x] Pebbles
- [x] Rocks (Small)
- [x] Rocks (Large)
