### ISSUE TITLE
Machina: Martian Planet Type

### ISSUE THREAD

**Issue by Cy4Shot** [Cy4Shot/MACHINA#13]
# Description
This task involves creating the second unique planet type for MACHINA. Martian planets have a red rock base, with rocky terrain, dead plants, salt deposits and sulfur geysers. High sulfur & salt contents may prove invaluable for automation, and geysers can provide a natural & renewable source of energy via the geothermal generator multiblock.

# Tasks
- [x] Sulfur Geyser Block
- [x] Porous Wastes Biome
- [x] Sandy Plains Biome
- [x] Salt Fields Biome
- [x] Crater Seas Biome
- [x] Biome Cleanup & Extra Blocks
