### ISSUE TITLE
Machina: Starchart T0

### ISSUE THREAD

**Issue by Cy4Shot** [Cy4Shot/MACHINA#15]
# Description
This task involves creating a to-scale 3D UI for rendering the generated starchart in-game.

# Aims
- To create a system for dynamically generating 3D planet textures and models.
- To create a to-scale system which allows for easy scaling and zooming.
- To create visually pleasing and user-friendly interface.
- To create a physically accurate star system and display useful information to the user about each planet.

# Tasks
- [x] Starchart Generation
- [x] Planet model rendering
- [x] Panning and zooming
- [x] Snap to planet
- [x] Orbit rendering
- [x] Icon rendering on zoom out
- [x] Planet info & extensible UI
